### ISSUE TITLE
[crucial] updating password triggers failed causes other parts of wallet broke.

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#10]
Description
1. In Password Settings, updating old password "aaaa1111?" to "aaaa2222?" triggers a message like blow:
![password error message](https://user-images.githubusercontent.com/42927489/53000080-766ff980-3462-11e9-86c9-8e7ed5211cf1.jpg)

2. When the message goes away, the wallet navigates to the Setting main screen.
3. Click Recovery Phrase, all the seed phrase disappears
4. Trying to update password again or trying re-login to the wallet, neither old password "aaaa1111?" or new password  "aaaa2222?" works.

**Comment by leoaion** [comment]
fix in 4f21ece657af3b9684b4ab903e79e7d27ba1b588

**Comment by MiaoShi09** [comment]
fix verified
