### ISSUE TITLE
The QR code in account is invalid

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#13]
Steps:
1. Phone A opens the wallet, navigate to an account
2. Phone B opens the wallet, navigate to an account and click SEND
3. Phone B in Send section， click[-] to open its camera to scan the QR code on Phone A

Result:
An alert message shows up saying it is an invalid QR code.

![172378021](https://user-images.githubusercontent.com/42927489/53007257-d91cc180-3471-11e9-99b4-504ea50e04a6.jpg)

**Comment by leoaion** [comment]
fixed in d8f4587bb0af597023dd800b34f35e053875770b

**Comment by MiaoShi09** [comment]
fix verified
