### ISSUE TITLE
Scan Screen is different between Recovery Section and Send Section

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#14]
The scan screen in Recovery Section contains a flashlight icon and a square to guide users where to place the QR Code.

While the scan screen is Send section only contains the pure camera view.

**Scan Screen in Send Section**
![1065632497](https://user-images.githubusercontent.com/42927489/53066566-72e47d00-350b-11e9-901f-4767d27ea4cd.jpg)

**Scan Screen in Recovery Section**
![670137612](https://user-images.githubusercontent.com/42927489/53066569-75df6d80-350b-11e9-8ef2-d6f8cda95b01.jpg)

**Comment by leoaion** [comment]
fixed in d8f4587bb0af597023dd800b34f35e053875770b

**Comment by MiaoShi09** [comment]
fix verified
