### ISSUE TITLE
Back button is able to navigate the screen from Home page to login/registration page

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#15]
**Steps:**
1. Login account/ create a new account, landing on Home page.
2. Click "Back" button on the phone.

**Expect:** the screen stays the Home section, it should not go to login, memorize recovery phrases page, or registration page.

**Actual:** the screen goes to whatever the previous pages, which means it can go back to  login, memorize recovery phrases page, or registration page.

**Comment by aion-chris** [comment]
update at d9659534f1e71a5cbe80d8e80de5ccc93cfd7b8b

**Comment by MiaoShi09** [comment]
fix verified
