### ISSUE TITLE
Clicking Copy button in Memorize Recovery Phrase does generate any message.

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#16]
In Memorize Recovery Phrase, clicking the Copy button.

**Expected:** the phone saves the phrases in its clipboard and displays a message to notify users.

**Actual:** the phone saves the phrases in the clipboard but no message shows up. It confuses users.

**Comment by aion-chris** [comment]
patch on 85b7274a272d78a475f4e2ea18dda2beba196dc4

**Comment by MiaoShi09** [comment]
fix verified
