### ISSUE TITLE
App crashes when trying to send a tx from a Ledger account to another account

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#20]
**Steps:**
1. import an account A from Ledge Nano, get some balance.
2. Send some value within account A's balance to another account.

**Expected:** the tx should be processed
**Actual:**  app crashed/exited itself, and the tx never be processed.

**Comment by leoaion** [comment]
fix in 5f667fc22be478bacb687abd19c23208d76d3c60

**Comment by MiaoShi09** [comment]
fix verified
