### ISSUE TITLE
Wallet name consistency and Typo in About page

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#23]
1. There are two Chinese name for this wallet in About page. 
2. "Power by Chaion" should be "Powered By Chaion"
![getimage 6](https://user-images.githubusercontent.com/42927489/53139921-0ed2bf00-35c6-11e9-86d6-43273056f094.jpeg)

**Comment by leoaion** [comment]
fix in 93c63518a2f7b5845a7cca6a5ddbd4b18f4e67d2

**Comment by MiaoShi09** [comment]
fix verified
