### ISSUE TITLE
In Password settings, Submit button need double-taps to triggler.

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#24]
Steps:
1. In Password Settings, tap a text field
2. Hide the keyboard
2. Single tap the Submit Button.

Expected: The form gets submitted and show a message of the submission result.

Actual: User need to tap someplace to exit the focus on the text field, then tap Submit button to submit the form.

**Comment by leoaion** [comment]
fix in 7b466792a4bc4ffa06623433e29de30c0e722511

**Comment by MiaoShi09** [comment]
fix verified
