### ISSUE TITLE
Importing accounts from Ledger does not refresh the balance of those accounts

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#28]
Steps:
1. Click (+) import from Ledger
2. Select the accounts of which balance is more than 0;
3. Click Import

Expected: The accounts show up in Wallet and their latest balance come up very soon.

Actual: The  ledger accounts require manually refresh to update their balances

**Comment by leoaion** [comment]
fixed in fd74f6ab66ca96a742f2c9c51872dc1dd3a8c183

**Comment by MiaoShi09** [comment]
fix verified
