### ISSUE TITLE
Import From Master Key is confusing

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#3]
When entering the new account, click (+) icon to add or import accounts. The first Import option "Master Key" is confusing. It actually adds the accounts that are generated from seed phrases(Mnemonic Phrases). Are we sure "Master Key" is the common name for seed phrases(Mnemonic Phrases)?

**Comment by Chengchcc** [comment]
update in 31b6ee3659e23f8421d6d0c714f4ea9398e9c533

**Comment by MiaoShi09** [comment]
"seed phrases" should be updated to "Seed Phrases"

**Comment by MiaoShi09** [comment]
Clicking Import From seed phrases, the new section title is still "Master Key"

**Comment by MiaoShi09** [comment]
fix verified
