### ISSUE TITLE
New account can view the previous user's balance

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#31]
Precondition: the previous user imported some accounts with a good amount balance.

Steps:
1. log out the account
2. register a new account

Expected: the wallet contains no account and the total balance is 0

Actual: the total balance is the amount of the previous user's balance

![getimage 3](https://user-images.githubusercontent.com/42927489/53475004-c32e8280-3aa9-11e9-99f4-786c9e52aab8.jpeg)

**Comment by leoaion** [comment]
fix in 362ff208eacd8dc4d2fd858b4db7ecc230456e88

**Comment by MiaoShi09** [comment]
fix verified
