### ISSUE TITLE
Keyboard always shows up on IOS

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#32]
Once clicking any text field, the cursor will stay focus on the text fields, which causes the digital keyboard stays on the screen and blocks other content.

Affect pages: Wallet, Password, service configuration, advance, login, registration, recovery

**Comment by leoaion** [comment]
fixed in d8f4daa59bafedf19ebecc53608308ab5774615d

keyboard will dismissed when click other area

**Comment by MiaoShi09** [comment]
verified on iPhone SE
