### ISSUE TITLE
Expected displaying a number keyboard for entering numbers

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#34]
Affected Section: Account/Send, Account/Receive, Settings/advance
![1637473916](https://user-images.githubusercontent.com/42927489/53788915-1434ef80-3f5e-11e9-9013-a6f595393f77.jpg)
![1030012002](https://user-images.githubusercontent.com/42927489/53788920-16974980-3f5e-11e9-9cc7-81a1bdd5fbaf.jpg)
![1548920136](https://user-images.githubusercontent.com/42927489/53788922-19923a00-3f5e-11e9-94c2-57b4061491ca.jpg)

**Comment by leoaion** [comment]
fixed in 59eb4cd2308f4a9f7faf34ea95f1456931c53c12

**Comment by MiaoShi09** [comment]
Focusing on Gas Price/Gas Limit field in Send page shows up a regular keyboard;

Verified other fields on Android.

**Comment by MiaoShi09** [comment]
passed on iPhone SE and HUAWEI VIE-AL10
