### ISSUE TITLE
Set login session timeouts and currency refresh interval to be 0

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#36]
It is meanless to accept 0 mins for login session timeouts and currency refresh interval.

**Comment by leoaion** [comment]
fixed in 69a890ff9092fb1261c828311bf063ecc71680ff 
session timeout and currency refresh interval must be > 0

**Comment by MiaoShi09** [comment]
Alert showing up as expected.

Need better Chinese warning message for login Session Timeout.
![getimage 8](https://user-images.githubusercontent.com/42927489/53942857-d15a4f80-40f6-11e9-8e42-cd7d8ec24186.jpeg)

**Comment by MiaoShi09** [comment]
passed on iPhone SE and Huawei VIE-AL10
