### ISSUE TITLE
When language is set to Chinese, the top content in wallet section is still in English.

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#4]
![1179267763](https://user-images.githubusercontent.com/42927489/52987319-8fae8100-3435-11e9-9d61-f3eaf7c5bbbc.jpg)

**Comment by MiaoShi09** [comment]
Similar issues at Login page and alert messages.
![1389013318](https://user-images.githubusercontent.com/42927489/52988446-4c0a4600-343a-11e9-87e5-f6c891d678e5.jpg)
![897767474](https://user-images.githubusercontent.com/42927489/52988462-575d7180-343a-11e9-9c88-8fd41248940a.jpg)

**Comment by MiaoShi09** [comment]
![getimage](https://user-images.githubusercontent.com/42927489/53138536-9cf87680-35c1-11e9-8b7c-c42d2c5d046a.jpeg)

![getimage 1](https://user-images.githubusercontent.com/42927489/53139472-b7801f00-35c4-11e9-93e5-1a578726353e.jpeg)

![getimage 2](https://user-images.githubusercontent.com/42927489/53139495-c8309500-35c4-11e9-8433-d86ab3ab1156.jpeg)
![getimage 3](https://user-images.githubusercontent.com/42927489/53139506-cc5cb280-35c4-11e9-8141-76e650681af8.jpeg)

**Comment by MiaoShi09** [comment]
fixed

**Comment by MiaoShi09** [comment]
registration remember phrase title

**Comment by leoaion** [comment]
no i18n for recovery/password and register/mneomoic pages.

**Comment by MiaoShi09** [comment]
![getimage 7](https://user-images.githubusercontent.com/42927489/53473430-544f2a80-3aa5-11e9-9d64-546301f0b6bf.jpeg)

**Comment by MiaoShi09** [comment]
register/mneomoic page title is always English on IOS

**Comment by MiaoShi09** [comment]
Error message for missing currency unit in wallet section.
![getimage 9](https://user-images.githubusercontent.com/42927489/53943469-221e7800-40f8-11e9-97cd-4f69f7956400.jpeg)
