### ISSUE TITLE
Mobile OS and app language is different from the default setting.

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#5]
My adroid OS language is Chinese. When I first launched the app, the menu and instructions were Chinese. But I navigate to language settings, the default value is English.

![1779255807](https://user-images.githubusercontent.com/42927489/52987391-e0be7500-3435-11e9-8dcd-131042450717.jpg)

**Comment by MiaoShi09** [comment]
**Related Issue:** updating Settings also updates language settings.

**Pre-condition:** OS language is Chinese while the Wallet default language is English. However, when the wallet displays the most content in Chinese when launching the app for the first time.

**Steps:** go to settings and update Service Configuration and click "save" button.

**Expected:** only updates the Service Configurations

**Actual:** the app content also changes to English

**Comment by leoaion** [comment]
fix in 2279d17b1483d6cce7d12c18478ce121c2e7c080

**Comment by MiaoShi09** [comment]
fix verified
