### ISSUE TITLE
default server ID is localhost(http://127.0.0.1:8545)

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#8]
In server settings, the wallet server is set to http://127.0.0.1:8545

![1513796988](https://user-images.githubusercontent.com/42927489/52989617-351a2280-343f-11e9-89c6-c4942bf5cbd4.jpg)

**Comment by leoaion** [comment]
update to https://api.nodesmith.io/v1/aion/mainnet/jsonrpc?apiKey=c8b8ebb4f10f40358b635afae72c2780
which is a nodesmith url under leo.ren@aion.network

**Comment by MiaoShi09** [comment]
fix verified

**Comment by MiaoShi09** [comment]
verified on IOS as well
