### ISSUE TITLE
unable to import from private key

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#9]
1. In Wallet section, click (+) to import from private keys.
2. Enter a private key "0x0e7ff5ec5e46ba057e0a9cfcb610a8560260fbfc2db92b08faba826dacac485eb6a639de25c0ca499d4161409b02f3a6e0ed0555bdbd56017f5fc9f3ce34e3d0"
3. Click "Import"

Expect: Go back to main wallet section, and a new account shows in the pages.

Actual: nothing happens, the page stays on the private key import page.

**Comment by leoaion** [comment]
fixed in 81909e106cbd99bbec8076ee1da77584cf33353c

**Comment by MiaoShi09** [comment]
fix verified
